"""
Django settings for MY project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
import MY.setting as setting


BASE_DIR = Path(__file__).resolve().parent.parent


SECRET_KEY = setting.SECRET_KEY
# 'rftr5t%cm!2htso9dawd=#7t8$=lb*q8rnb#^z+4*&h13kjq5u'


DEBUG = True

ALLOWED_HOSTS = ['*']


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'six',
    'ckeditor_uploader',
    'ckeditor',
    'django.contrib.sites',
    'disqus',
    'blog',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'MY.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MY.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = setting.DATABASES


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

# email 인증

EMAIL_HOST = 'smtp.gmail.com' 		     # 메일 호스트 서버
EMAIL_PORT = '587'                       # 서버 포트
EMAIL_HOST_USER = setting.EMAIL_HOST_USER 	 # 우리가 사용할 Gmail
EMAIL_HOST_PASSWORD = setting.EMAIL_HOST_PASSWORD		 # 우리가 사용할 Gmail p
EMAIL_USE_TLS = True			         # TLS 보안 설정
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# CKEDIROT FILE PATH
CKEDITOR_UPLOAD_PATH = 'uploads/'


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ckeditor setting
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'height': 400,
        'width': '100%',
        'toolbar_Custom': [
            ["Styles",
             "Format",
             "Bold",
             "Italic",
             "Underline",
             "Strike",
             "SpellChecker",
             "Undo",
             "Redo", ],
            ["Link", "Unlink", "Anchor"],
            ["Image", "Flash", "Table", "HorizontalRule"],
            ["TextColor", "BGColor"],
            ['CodeSnippet'],
            ['JustifyLeft', 'JustifyCenter', 'JustifyRight'],
            ["Smiley", "SpecialChar"],
            ['Source'],
        ],
        'extraPlugins': ','.join(
            [
                'codesnippet',
            ]),
    },
}

# CKEDITOR_CONFIGS = {
#     'default': {
#         'toolbar': 'full',
#         'extraPlugins': ','.join(
#             [
#                 'codesnippet',
#             ]),
#     },
# }

# disqus setting
DISQUS_WEBSITE_SHORTNAME = 'junjuniy'
SITE_ID = 1
